version: 2

project_name: spec2llms

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/spec2llms
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - repository:
      owner: mdwitr0
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/mdwitr0/spec2llms"
    description: "Generate llms.txt from OpenAPI/Swagger specifications"
    license: "MIT"
    install: |
      bin.install "spec2llms"
    test: |
      system "#{bin}/spec2llms", "--version"
